### ISSUE TITLE
Error Duolingo

### ISSUE THREAD

**Issue by babsacademy** [jakecreps/poastal#11]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/poastal/backend/poastal.py", line 13, in <module>
    from duolingo import duolingo_name_check, duolingo_email, duolingo_image
ImportError: cannot import name 'duolingo_image' from 'duolingo' (/data/data/com.termux/files/home/poastal/backend/modules/duolingo.py)

**Comment by rufflabs** [comment]
Same here. Looks like the `duolingo.py` doesn't have the `duolingo_image` function defined. 

I went back to the April 7 commit and it works.

**Comment by turnkit** [comment]
same:

Traceback (most recent call last):
  File "/home/david/poastal/backend/./poastal.py", line 13, in <module>
    from duolingo import duolingo_name_check, duolingo_email, duolingo_image
ImportError: cannot import name 'duolingo_image' from 'duolingo'

**Comment by jakecreps** [comment]
Thanks for reporting this everyone. I goofed and forgot to merge the code change in duolingo.py to include the new function. It's fixed now.
