### ISSUE TITLE
No UI at http://127.0.0.1:8080/ but just "No email address provided."

### ISSUE THREAD

**Issue by turnkit** [jakecreps/poastal#12]
After starting the python script and navigating to http://127.0.0.1:8080/ there is no option to enter an email address but only the message,  "No email address provided."

**Comment by jakecreps** [comment]
That's not for the UI, that's for the Flask app. Open index.html in the root directory in order to get the UI. That index.html file fetches the Flask URL and populates the results on the page.

**Comment by Grip** [comment]
Hi,
same problem here:

 curl -v 127.0.0.1:8080/index.html
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /index.html HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 NOT FOUND
< Server: Werkzeug/2.3.3 Python/3.9.2
< Date: Tue, 02 May 2023 10:12:21 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 207
< Access-Control-Allow-Origin: *
< Connection: close
<
<!doctype html>
<html lang=en>
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
* Closing connection 0

I surely must me doing something wrong here...
